---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  pull: always
  settings:
    restore: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_{{ arch }}_{{ os }}'
    bucket: drone-cache-demo
    region: ap-northeast-1
    mount:
      - 'drone-cache'

- name: build
  pull: always
  image: golang:1.15-rc
  commands:
  - go build -v -a -o demo
  environment:
    CGO_ENABLED: 0
    GOMODCACHE: 'drone-cache'
  when:
    event:
      exclude:
      - tag

- name: rebuild-cache
  image: meltwater/drone-cache
  pull: always
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  settings:
    rebuild: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "go.mod" }}_{{ checksum "go.sum" }}_{{ arch }}_{{ os }}'
    bucket: drone-cache-demo
    region: ap-northeast-1
    mount:
      - 'drone-cache'

# - name: default-publish
#   pull: always
#   image: plugins/docker:linux-amd64
#   settings:
#     auto_tag: true
#     cache_from: appleboy/gin-docker-demo
#     daemon_off: false
#     dockerfile: Dockerfile
#     password:
#       from_secret: docker_password
#     repo: appleboy/gin-docker-demo
#     username:
#       from_secret: docker_username
#   when:
#     event:
#       exclude:
#       - pull_request

# - name: docker-buildkit
#   pull: always
#   image: plugins/docker:linux-amd64
#   environment:
#     DOCKER_BUILDKIT: 1
#   settings:
#     auto_tag: true
#     daemon_off: false
#     dockerfile: Dockerfile.buildkit
#     password:
#       from_secret: docker_password
#     repo: appleboy/gin-docker-buildkit
#     username:
#       from_secret: docker_username
#   when:
#     event:
#       exclude:
#       - pull_request
